#! /bin/sh
#
# Download dependencies needed to compile s3lib.
#
# Usage: download-deps [PREFIX]
#
# The PREFIX is the directory where dependencies will be downloaded to. It defaults
# to /opt/logicblox, but can be overridden by setting BLOXWEB_DEPS or by passing a
# parameter to this script.

set -e

PREFIX=$BLOXWEB_DEPS

if [ -z "$PREFIX" ]; then
    PREFIX=/opt/logicblox/deps
fi

if [ -n "$1" ]; then
    PREFIX="$1"
fi

echo "Downloading dependencies to $PREFIX"

mkdir -p $PREFIX
cd $PREFIX

echo "Downloading guava..."
mkdir -p guava-15.0/lib/java
curl -o guava-15.0/lib/java/guava-15.0.jar \
   http://search.maven.org/remotecontent?filepath=com/google/guava/guava/15.0/guava-15.0.jar

echo "Downloading log4j..."
mkdir -p log4j-1.2.13/lib/java
curl -o log4j-1.2.13/lib/java/log4j-1.2.13.jar \
   http://mirrors.ibiblio.org/maven2/log4j/log4j/1.2.13/log4j-1.2.13.jar

echo "Downloading jcommander..."
mkdir -p jcommander-1.29/lib/java
curl -o jcommander-1.29/lib/java/jcommander-1.29.jar \
   http://search.maven.org/remotecontent?filepath=com/beust/jcommander/1.29/jcommander-1.29.jar

echo "Downloading commons-io..."
mkdir -p commons-io-2.4/lib/java
curl -o commons-io-2.4/lib/java/commons-io-2.4.jar \
   http://repo1.maven.org/maven2/commons-io/commons-io/2.4/commons-io-2.4.jar

echo "Downloading commons-codec..."
mkdir -p commons-codec-1.9/lib/java
curl -o commons-codec-1.9/lib/java/commons-codec-1.9.jar \
   http://repo1.maven.org/maven2/commons-codec/commons-codec/1.9/commons-codec-1.9.jar

echo "Downloading aws-java-sdk..."

name="aws-java-sdk-1.7.1"
rm -rf ${name}
mkdir -p ${name}/lib/java
pushd ${name}/lib/java
curl -O http://sdk-for-java.amazonwebservices.com/${name}.zip
unzip ${name}.zip
for j in $(find ${name} -name '*.jar'); do
  cp $j .
done
rm -rf ${name}
popd
