#!/usr/bin/env bash
set -e
set -u

# nixpkgs needs to point to nixpkgs version 17.03,
# e.g. /home/user/dev/nix/nixpkgs-20170404
nixpkgs="$1"

# This wraps use of nix-build to run the test job in default.nix, passing in
# args that point to local source directories.

# clean up stuff that we don't want copied into the nix environment
rm -rf build Makefile buildlib.pyc

# set the "keep" flag if you don't want the test execution directory to be discarded
#keep="-K"

nix-build $keep -I nixpkgs=$nixpkgs -A test default.nix
