#!/usr/bin/env bash
set -e

# This wraps use of nix-build to run the test job in default.nix, passing in
# args that point to my local source directories.


# builder_config needs to point to a local copy of the logicblox/builder-config repository
builder_config="/home/weshunter/dev/nix-builds/config"


# clean up stuff that we don't want copied into the nix environment
rm -rf core build Makefile buildlib.pyc config-env.sh

# set the "keep" flag if you don't want the test execution directory to be discarded
#keep="-K"

# pkgs needs to point to nixpkgs version 17.03
pkgs="-I nixpkgs=/home/weshunter/dev/nix/nixpkgs-20170404"

nix-build $keep $pkgs -A run_test --argstr src_builder_config $builder_config test_wrapper.nix
