#! /bin/sh

set -u
set -e

usage()
{
  echo "Generates a public/private keypair for s3tool using openssl"
  echo "Usage: s3lib-keygen name"
}


if test $# -ne 1; then
  usage
  exit 1
fi

if test "$1" = "--help"; then
  usage
  exit 0
fi

if test "$1" = "-h"; then
  usage
  exit 0
fi

name=$1

if test -e "$name.pem"; then
  echo "File $name.pem already exists."
  exit 1
fi

priv=.s3lib-tmp-priv.pem
result=.s3lib-tmp.pem

openssl genrsa -out $priv 2048
openssl rsa -in $priv -out $result -pubout
echo "" >> $result
openssl pkcs8 -topk8 -inform PEM -outform PEM -in $priv -nocrypt >> $result
echo "" >> $result

rm -f $priv
mv $result $name.pem

echo "Created $name.pem"
