#!/usr/bin/env python

import sys
import os
import subprocess
import argparse

bindir = os.path.dirname(os.path.realpath( __file__ ))
prefix = os.path.dirname(bindir)

def run(args):
    deps = ['s3lib-0.1.jar',
            'jcommander-1.29.jar',
            'guava-13.0.1.jar',
            'commons-logging-1.1.1.jar',
            'httpcore-4.1.jar',
            'httpclient-4.1.1.jar',
            'commons-codec-1.6.jar',
            'log4j-1.2.13.jar',
            'aws-java-sdk-1.3.18.jar']

    deps_paths = [prefix +'/lib/java/' + name for name in deps]
    classpath = ':'.join(deps_paths)

    subenv = os.environ.copy()
    subenv['S3LIB_HOME'] = prefix

    java_args = ['java', '-cp', classpath, 'com.logicblox.s3lib.Main']
    java_args.extend(args)

    os.execvpe('java', java_args, subenv)

def main():
    command_line = sys.argv[1:]
    run(command_line)

if __name__ == '__main__':
    main()
